"""empty message

Revision ID: 9e6ca30f2063
Revises: 
Create Date: 2018-11-13 22:12:44.244690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e6ca30f2063'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hubuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.Integer(), nullable=True),
    sa.Column('authority', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account'),
    sa.UniqueConstraint('username')
    )
    op.create_table('member',
    sa.Column('memberNo', sa.Integer(), nullable=False),
    sa.Column('memberName', sa.String(length=32), nullable=True),
    sa.Column('academy', sa.String(length=80), nullable=True),
    sa.Column('direction', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('memberNo'),
    sa.UniqueConstraint('memberName')
    )
    op.create_table('essay',
    sa.Column('essayNo', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('updatetime', sa.Date(), nullable=True),
    sa.Column('author', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['member.memberName'], ),
    sa.PrimaryKeyConstraint('essayNo'),
    sa.UniqueConstraint('title')
    )
    op.create_table('project',
    sa.Column('projectNo', sa.Integer(), nullable=False),
    sa.Column('projectName', sa.String(length=80), nullable=True),
    sa.Column('projectleader', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['projectleader'], ['member.memberName'], ),
    sa.PrimaryKeyConstraint('projectNo'),
    sa.UniqueConstraint('projectName')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    op.drop_table('essay')
    op.drop_table('member')
    op.drop_table('hubuser')
    # ### end Alembic commands ###
