"""empty message

Revision ID: ed579e5b057e
Revises: 9e6ca30f2063
Create Date: 2018-11-15 20:56:24.806049

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed579e5b057e'
down_revision = '9e6ca30f2063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Essay',
    sa.Column('essayNo', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=16), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('updatetime', sa.Date(), nullable=True),
    sa.Column('author', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('essayNo'),
    sa.UniqueConstraint('title')
    )
    op.create_table('ProjectEssay',
    sa.Column('pro_essayNo', sa.Integer(), nullable=False),
    sa.Column('essayNo', sa.Integer(), nullable=True),
    sa.Column('pro_design', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['essayNo'], ['Essay.essayNo'], ),
    sa.PrimaryKeyConstraint('pro_essayNo')
    )
    op.drop_index('title', table_name='essay')
    op.drop_table('essay')
    op.add_column('member', sa.Column('experience', sa.String(length=150), nullable=True))
    op.add_column('member', sa.Column('language', sa.String(length=40), nullable=True))
    op.add_column('member', sa.Column('software', sa.String(length=40), nullable=True))
    op.add_column('project', sa.Column('howmany', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('projectMan', sa.String(length=10), nullable=True))
    op.add_column('project', sa.Column('time', sa.Date(), nullable=True))
    op.drop_constraint('project_ibfk_1', 'project', type_='foreignkey')
    op.drop_column('project', 'projectleader')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('projectleader', mysql.VARCHAR(length=16), nullable=True))
    op.create_foreign_key('project_ibfk_1', 'project', 'member', ['projectleader'], ['memberName'])
    op.drop_column('project', 'time')
    op.drop_column('project', 'projectMan')
    op.drop_column('project', 'howmany')
    op.drop_column('member', 'software')
    op.drop_column('member', 'language')
    op.drop_column('member', 'experience')
    op.create_table('essay',
    sa.Column('essayNo', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('body', mysql.TEXT(), nullable=True),
    sa.Column('updatetime', sa.DATE(), nullable=True),
    sa.Column('author', mysql.VARCHAR(length=32), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['member.memberName'], name='essay_ibfk_1'),
    sa.PrimaryKeyConstraint('essayNo'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('title', 'essay', ['title'], unique=True)
    op.drop_table('ProjectEssay')
    op.drop_table('Essay')
    # ### end Alembic commands ###
